services:
  - type: web
    name: ai-gateway-api
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ai-gateway-db
          property: connectionString
      - key: CLAUDE_API_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: NVIDIA_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: HF_API_KEY
        sync: false
      - key: API_KEY
        sync: false

databases:
  - name: ai-gateway-db
    plan: free
    databaseName: aigateway
    user: aigateway
